### ISSUE TITLE
Does this need to be specific to package.json?

### ISSUE THREAD

**Issue by ctrlplusb** [cameronhunter/prettier-package-json#1]
Or could it be generically used for any json structure?

**Comment by cameronhunter** [comment]
I named it for `package.json` because I wanted it to have a consistent (and preferential) order for keys within that file. In a future release I'd also like it to rewrite some fields, e.g. split or join the author field, simplify repository links, order pre and post scripts sensibly.

It can currently be used generically for any JSON structure/file, either as a library or via the command line, however, its options will become more specific to `package.json` in future releases.

Library usage:
```javascript
const { format } = require('prettier-package-json');

const obj = {
  baz: 'baz',
  foo: 'foo',
  bar: 'bar'
};

format(obj, { keyOrder: ['foo', 'bar', 'baz'] });
```

CLI usage:
```sh
$ prettier-package-json --key-order foo,bar,baz my-file.json
```

Currently the module is very simple and is really just providing an interface to [sort-object-keys](npmjs.com/package/sort-object-keys). If you're looking for a library that just sorts objects, then I recommend using it.
