### ISSUE TITLE
please explain the reasoning behind the "opinionated order"

### ISSUE THREAD

**Issue by revelt** [cameronhunter/prettier-package-json#4]
Correct me if I'm wrong, but according to this _opinionated_ setup, not always `dependencies` and `devdependencies` are the last keys in `package.json`. We have keys following them:

    'keywords',
    'engines',
    'engine-strict',
    'engineStrict',
    'os',
    'cpu',
    'publishConfig'

Now the reason why we put things at the bottom is _easy access_ for consumers.

@cameronhunter With full respect, Cameron, please explain to all the visitors here why do you need easier access to `engines`, `os` or `cpu` instead of `dependencies` and `devdependencies`? 

My arguments **against** this are: `engines` should be a badge in readme anyway, `keywords` are set only once and matter only to author (so putting that at the bottom is quite egotist thing to do), `os`/`cpu` are never used.

One more observation; I noticed that your all of your own libraries are not using this order, for example, (local-ssl-proxy)[https://github.com/cameronhunter/local-ssl-proxy] - on the contrary, they have the old sensible order in package.json with `dependencies` and `devdependencies` at the bottom.

**Comment by cameronhunter** [comment]
In no place does the README say that `dependencies` and `devDependencies` are the last keys in `package.json`. The README states:

> Keys in package.json will be sorted in an [opinionated order](https://github.com/cameronhunter/prettier-package-json/blob/master/src/defaultOptions.js) but may be configured to your own preferences.

The reason that I clearly state the defaults are opinionated is because, in my opinion, it's the most helpful order (most important → least important). If you're unhappy with the ordering you can configure it to use whatever key order you want.

As an aside, your attitude and condescension is unnecessary and unwelcome. If this package doesn't fit your needs, create a PR, use another package, or write your own.
