### ISSUE TITLE
Package sort order different than npm install

### ISSUE THREAD

**Issue by csandman** [cameronhunter/prettier-package-json#54]
For my current project, I've been noticing the sort order of my packages change every time I run `npm install`.  Specifically in this case, this package sorts dashes before underscores but `npm install` puts underscores first.  It would be ideal if these followed the same convention.

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/9214195/158459103-bfa2a6c4-0e89-4d51-80e5-2af3dcb7a315.png">

`prettier-package-json` -> `npm install`

**Comment by yinzara** [comment]
Yes we have this exact same problem. It seems that the sorting of the "-" vs the "_" characters are the real issue.  When you have a package.json with both, you get this behavior.

**Comment by yinzara** [comment]
Looks like this is happening because the `src/sort-dependencies.ts` sorts using the function:
```
function order(a: string, b:string) {
  return a.localeCompare(b, 'en');
}
```

To sort the list, but using the following function we can see that it has an opposite effect with "-" vs "_" than just using the default sort order:
```javascript
const a = 'a';
const b = 'grpc_tools_node_protoc_ts'; // With accents, lowercase
const c = 'grpc-web'; // No accents, uppercase
const d = 'z';

function sortByLocale(a, b) {
  return a.localeCompare(b, 'en');
}

const sorted = [a, b, c, d].sort();
const sortedByLocale = [a, b, c, d].sort(sortByLocale);
console.log("Sorted:",sorted);
console.log("SortedByLocale:",sortedByLocale);
```

Outputs:
```
> "Sorted:" Array ["a", "grpc-web", "grpc_tools_node_protoc_ts", "z"]
> "SortedByLocale:" Array ["a", "grpc_tools_node_protoc_ts", "grpc-web", "z"]
```

I believe if we simply change the src/dependency.ts to not pass a sort function and instead use the default sorting that we will get consistent behavior.

Thoughts?

**Comment by yinzara** [comment]
I have created a PR with tests that changes the behavior to just use "sort()" and now added tests when there were none for this existing functionality.
